### ISSUE TITLE
Imported images

### ISSUE THREAD

**Issue by CodyTolene** [sbrin/lopaka#10]
Once sized and positioned, how do I export the imported image for use on the Flipper Zero?

Thanks

**Comment by sbrin** [comment]
@CodyTolene you have to manually put the original image in your flipper application assets folder.

Check this tutorial (a bit old though) for more details: https://twitter.com/ilin_pt/status/1604486123153231872?s=20

**Comment by CodyTolene** [comment]
@sbrin  Thank you!
