### ISSUE TITLE
Colored image (icon) option

### ISSUE THREAD

**Issue by Dianwijaya123** [sbrin/lopaka#102]
Small feature but if added it is very nice

**Comment by sbrin** [comment]
@Dianwijaya123 can you describe a use case for that?

What library do you use with colored bitmaps?

**Comment by Dianwijaya123** [comment]
If the bitmap selected, it's show color option in the right like the
String, Rect, etc.
I use default Adafruit_SSD1306 Library,

Pada Kam, 8 Feb 2024 pukul 21.14 Mikhail Ilin ***@***.***>
menulis:

**Comment by sbrin** [comment]
@Dianwijaya123 it is already there

<img width="992" alt="Screenshot 2024-02-08 at 18 10 44" src="https://github.com/sbrin/lopaka/assets/1325864/3f87ef9f-f299-4078-a1f5-de419e831e8f">

**Comment by Dianwijaya123** [comment]
![ed](https://github.com/sbrin/lopaka/assets/70804570/1a060e9e-c813-4f4f-b246-cc305230f028)

I'd need like that one (It's edited btw)

**Comment by sbrin** [comment]
Implemented, available on dev.lopaka.app

Will be deployed to live in a couple of days
