### ISSUE TITLE
develop lost the displayed x coordinates on top of the preview screen

### ISSUE THREAD

**Issue by Gaai** [sbrin/lopaka#130]
<img width="244" alt="Schermafbeelding 2024-02-25 224017" src="https://github.com/sbrin/lopaka/assets/59128156/edef4f16-f544-4861-b207-77983f765ebd">

**Comment by deadlink** [comment]
Fixed in #131

**Comment by sbrin** [comment]
thank you

**Comment by sbrin** [comment]
@Gaai yep, I messed it up. Check this hotfix please #149
