### ISSUE TITLE
Vertical Flipper Zero display support

### ISSUE THREAD

**Issue by grafovdenis** [sbrin/lopaka#2]
Hey Mikhail,
Thanks for the great project you make!

What do you think about vertical Flipper Zero display support(64x128) in the project?
I suppose, it would be great option to select vertical/horizontal display (as with U8g2).

**Comment by sbrin** [comment]
Hi. Thanks for sharing. Yep this feature is in the shortlist. Need to find a nice visual representation for such a switch

**Comment by sbrin** [comment]
Currently to work with vertical orientation I recommend to set the display to 64x128
