### ISSUE TITLE
Add more fonts

### ISSUE THREAD

**Issue by sbrin** [sbrin/lopaka#51]
- Check u8g2 library fonts
- Find the most popular/useful fonts
- Add 10 more fonts to editor

**Comment by Gaai** [comment]
Is this helpful? 
https://github.com/tomchen/bdfparser-js

Test with the live online editor: 
https://font.tomchen.org/bdfparser_js/editor

```
<BDF
fontfile='https://raw.githubusercontent.com/olikraus/u8g2/master/tools/font/bdf/9x15.bdf'
pixelcolors={{
  0: 'white',
  1: 'black',
  2: null,
}}
size={2}
func={
  (font, {Font, Glyph, Bitmap, $Font, $Glyph, $Bitmap}) => {
    return font.draw('Hello, might this be what you are looking for? Seems to work quite well with all kinds of BDF files. And custom ones aswell ;) 1234567890 €10,- 18°C', {linelimit: 242}).glow(0)
  }
}/>
```

**Comment by sbrin** [comment]
@Gaai thank you, we saw this lib and decided to use our own, it's almost done now, check this PR https://github.com/sbrin/lopaka/pull/70

**Comment by sbrin** [comment]
New fonts were merged into develop https://dev.lopaka.app/

Will be released soon
