### ISSUE TITLE
U8g2 and Uint32 Raw not working in firefox

### ISSUE THREAD

**Issue by Greeniac** [sbrin/lopaka#58]
using Debain 12 with FireFox, U8g2 and Uint32 Raw are grayed out and i cannot use it, i can select it and the code converts to U8g2 but i cannot draw anything, the whole display area is grayed out, but in chromium it works just fine.

**Comment by sbrin** [comment]
Thank you! Fix is ready to deploy

**Comment by sbrin** [comment]
@Greeniac it should be fixed now, please check

**Comment by Greeniac** [comment]
Yeah it works, thanks!
