### ISSUE TITLE
Costom resolution support 

### ISSUE THREAD

**Issue by CodeExplorer123** [sbrin/lopaka#68]
Hello, 
I'm a new user working on an e-paper display project and loving your program! However, I'm stuck with a display that operates at 250x122 pixels, which isn't currently supported. 
Adding this resolution option would be a huge help, however maybe it's possible to implement an option for custom resolutions?

Thanks!

**Comment by sbrin** [comment]
Thank you for your feedback. We've added this size recently after your request 🤗

Will think about custom size. I like this idea
