### ISSUE TITLE
UINT32 RAW CODE NOT SHOWING https://lopaka.app/

### ISSUE THREAD

**Issue by didotkuh** [sbrin/lopaka#72]
![NOTSHOW](https://github.com/sbrin/lopaka/assets/101709005/98e249f8-b8a5-4e08-a6c4-e179f2bebb45)

**Comment by sbrin** [comment]
I can clearly see the code.

uint32 raw mode means it renders the whole screen as a single bitmap array.

Probably you need something like AdafruitGFX or U8g2
