### ISSUE TITLE
Support for esp-idf C-style formatting and esp32 bitmap tables without PROGMEM

### ISSUE THREAD

**Issue by Gaai** [sbrin/lopaka#85]
Would be real nice if there would be an option to select C-style formatting for the use with esp32 and esp-idf. Using the underscore and &object notation:
```
	u8g2_ClearBuffer(&u8g2);
	u8g2_SetBitmapMode(&u8g2, 1); // transparent bitmaps
    u8g2_SetContrast(&u8g2, 255); // set display contrast/brightness
    u8g2_DrawXBM(&u8g2, ...);
    u8g2_SetFont(&u8g2, ...);
    u8g2_DrawStr(&u8g2, ...);
    u8g2_SendBuffer(&u8g2);
```
And instead of `static const unsigned char image_Error_18x18_bits[] U8X8_PROGMEM`. Just:
`const uint8_t image_Error_18x18_bits[]`

**Comment by sbrin** [comment]
We can start from just adding a new platform with new U8G2 formatting.

But logically it is more like a subset of U8G2 platform. So it can be a code export configuration option. See screenshot below:

<img width="978" alt="Screenshot 2024-01-24 at 14 20 23" src="https://github.com/sbrin/lopaka/assets/1325864/24359879-0a8b-46a3-821c-83e24ed2664c">

@Gaai how do you think we should call these two options? 

@deadlink what do you think?

**Comment by Gaai** [comment]
@sbrin Yeah good question. We've got possible different boards (with different memory layouts), platforms and programming languages. Perhaps it's a bit much if you put them all in categories like:
-board: arduino, esp32, stm32, risc-v, teensy etc;
-platform: arduino, platformio, esp-idf;
-programming language: cpp, c, (micro)python... 

So a simple choice between arduino style (cpp) and esp-idf style (c) would be a good start?
-Arduino AVR (Cpp PROGMEM); 
-Arduino/Esp32 (Cpp); // without PROGMEM
-Esp-Idf (C); 
And is perhaps all that's needed for the code layout enabling copy-paste to any project. Esp-idf can work with Cpp too but then the second choice would work for that. Don't know about u8g2 for (mycro)python... So left that out. Haven't worked with stm32 or teensy so not sure what applies there...

**Comment by sbrin** [comment]
Implemented, available on dev.lopaka.app

Will be deployed to live in a couple of days

@Gaai could you please check if it works as expected?

**Comment by Gaai** [comment]
I will

**Comment by Gaai** [comment]
Looks good, will try on actual device later. An option to not declare all image arrays as static would be nice. On esp-idf you would typically split code over multiple files and libraries. Seems preferable to me at least to declare the image arrays globally, so I can refer to them from mutliple files.

**Comment by Gaai** [comment]
@sbrin Found a problem: 
`u8g2_setFont` should be:
`u8g2_SetFont`

**Comment by Gaai** [comment]
Also (am I the only one encountering this?) the font names are wrong, at least for esp-idf. 
`u8g2_SetFont(&u8g2, u8g2_font_5x8);`
u8g2_font_5x8 doesn't exist. It's either: u8g2_font_5x8_tf, u8g2_font_5x8_tr, or u8g2_font_5x8_tn. 
In general I think you are looking for: 
`u8g2_SetFont(&u8g2, u8g2_font_5x8_tr);`

**Comment by deadlink** [comment]
> @sbrin Found a problem: `u8g2_setFont` should be: `u8g2_SetFont`

Oh it's my fault, i will fix it and fonts also
Just need to add _tr? right?

**Comment by Gaai** [comment]
Another thing. There should be a `u8g2_SendBuffer(&u8g2);` at the end of a drawing sequence right? And probably good idea to add a `u8g2_ClearBuffer(&u8g2);` at the start?

**Comment by deadlink** [comment]
Yes, I think it's a good idea

**Comment by deadlink** [comment]
Fixed in #134

**Comment by sbrin** [comment]
@Gaai I always thought that Buffer operations were optional. I don't have it in my arduino sketches at all. Is that always needed for ESP-idf?

**Comment by Gaai** [comment]
@sbrin U8g2 supports three different drawing modes:

1. Full screen buffer mode: F in constructor, use: `u8g2.clearBuffer() + u8g2.sendBuffer()` or `u8g2.updateDisplay(); ` or `u8g2.updateDisplayArea();` in program. Memory heavy but fast. 
2. Page mode (This is the U8glib picture loop): 1 in constructor, use:
 ```
u8g2.firstPage();
do{
   ....drawOperations....
} while (u8g2.nextPage()); 
```
 in program. More memory efficient but slow. 

 3. U8x8, character only mode: U8x8 constructor, all drawing functions write directly to display. 

https://github.com/olikraus/u8g2/wiki/setup_tutorial

**Comment by Gaai** [comment]
Perhaps you've been using U8x8 mode yourself? It says however that this mode doesn't support graphics and is not available for all displays. For me the buffer operations have been needed both on arduino and esp-idf. I've just tested some examples on Wokwi and confirmed it is needed on arduino too, using the u8g2 constructor type.

**Comment by sbrin** [comment]
Thank you for explanation. In one of my project there is only sendBuffer call. In others I use the Page mode. Now it's clear.
